# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(815, 528)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("egg.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.chk_remember = QtGui.QCheckBox(self.centralwidget)
        self.chk_remember.setGeometry(QtCore.QRect(10, 170, 161, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.chk_remember.setFont(font)
        self.chk_remember.setObjectName(_fromUtf8("chk_remember"))
        self.list_networks = QtGui.QComboBox(self.centralwidget)
        self.list_networks.setGeometry(QtCore.QRect(10, 80, 251, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.list_networks.setFont(font)
        self.list_networks.setObjectName(_fromUtf8("list_networks"))
        self.btn_scan = QtGui.QPushButton(self.centralwidget)
        self.btn_scan.setGeometry(QtCore.QRect(10, 40, 111, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.btn_scan.setFont(font)
        self.btn_scan.setObjectName(_fromUtf8("btn_scan"))
        self.btn_connect_wifi = QtGui.QPushButton(self.centralwidget)
        self.btn_connect_wifi.setGeometry(QtCore.QRect(270, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.btn_connect_wifi.setFont(font)
        self.btn_connect_wifi.setObjectName(_fromUtf8("btn_connect_wifi"))
        self.lndt_password = QtGui.QLineEdit(self.centralwidget)
        self.lndt_password.setGeometry(QtCore.QRect(10, 130, 251, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.lndt_password.setFont(font)
        self.lndt_password.setText(_fromUtf8(""))
        self.lndt_password.setObjectName(_fromUtf8("lndt_password"))
        self.btn_refresh_comm = QtGui.QPushButton(self.centralwidget)
        self.btn_refresh_comm.setGeometry(QtCore.QRect(510, 40, 31, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(18)
        self.btn_refresh_comm.setFont(font)
        self.btn_refresh_comm.setObjectName(_fromUtf8("btn_refresh_comm"))
        self.btn_connect_serial = QtGui.QPushButton(self.centralwidget)
        self.btn_connect_serial.setGeometry(QtCore.QRect(690, 130, 111, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.btn_connect_serial.setFont(font)
        self.btn_connect_serial.setObjectName(_fromUtf8("btn_connect_serial"))
        self.list_baud = QtGui.QComboBox(self.centralwidget)
        self.list_baud.setGeometry(QtCore.QRect(510, 130, 79, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.list_baud.setFont(font)
        self.list_baud.setObjectName(_fromUtf8("list_baud"))
        self.list_baud.addItem(_fromUtf8(""))
        self.list_baud.addItem(_fromUtf8(""))
        self.list_baud.addItem(_fromUtf8(""))
        self.list_baud.addItem(_fromUtf8(""))
        self.list_comm = QtGui.QComboBox(self.centralwidget)
        self.list_comm.setGeometry(QtCore.QRect(560, 40, 241, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.list_comm.setFont(font)
        self.list_comm.setObjectName(_fromUtf8("list_comm"))
        self.lbl_serial_connected = QtGui.QLabel(self.centralwidget)
        self.lbl_serial_connected.setGeometry(QtCore.QRect(560, 10, 16, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_serial_connected.setFont(font)
        self.lbl_serial_connected.setObjectName(_fromUtf8("lbl_serial_connected"))
        self.lbl_baud_rate = QtGui.QLabel(self.centralwidget)
        self.lbl_baud_rate.setGeometry(QtCore.QRect(510, 110, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.lbl_baud_rate.setFont(font)
        self.lbl_baud_rate.setObjectName(_fromUtf8("lbl_baud_rate"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(470, 10, 20, 191))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(7, 190, 801, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.lbl_serial = QtGui.QLabel(self.centralwidget)
        self.lbl_serial.setGeometry(QtCore.QRect(575, 10, 121, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.lbl_serial.setFont(font)
        self.lbl_serial.setObjectName(_fromUtf8("lbl_serial"))
        self.lbl_wifi = QtGui.QLabel(self.centralwidget)
        self.lbl_wifi.setGeometry(QtCore.QRect(25, 10, 121, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.lbl_wifi.setFont(font)
        self.lbl_wifi.setObjectName(_fromUtf8("lbl_wifi"))
        self.lbl_wifi_connected = QtGui.QLabel(self.centralwidget)
        self.lbl_wifi_connected.setGeometry(QtCore.QRect(10, 10, 16, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_wifi_connected.setFont(font)
        self.lbl_wifi_connected.setObjectName(_fromUtf8("lbl_wifi_connected"))
        self.chk_show = QtGui.QCheckBox(self.centralwidget)
        self.chk_show.setGeometry(QtCore.QRect(270, 130, 131, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.chk_show.setFont(font)
        self.chk_show.setObjectName(_fromUtf8("chk_show"))
        self.btn_start_acquisition = QtGui.QPushButton(self.centralwidget)
        self.btn_start_acquisition.setGeometry(QtCore.QRect(220, 450, 120, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.btn_start_acquisition.setFont(font)
        self.btn_start_acquisition.setObjectName(_fromUtf8("btn_start_acquisition"))
        self.lbl_acquisition_2 = QtGui.QLabel(self.centralwidget)
        self.lbl_acquisition_2.setGeometry(QtCore.QRect(25, 210, 121, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.lbl_acquisition_2.setFont(font)
        self.lbl_acquisition_2.setObjectName(_fromUtf8("lbl_acquisition_2"))
        self.lbl_acquisition = QtGui.QLabel(self.centralwidget)
        self.lbl_acquisition.setGeometry(QtCore.QRect(10, 210, 16, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_acquisition.setFont(font)
        self.lbl_acquisition.setObjectName(_fromUtf8("lbl_acquisition"))
        self.scanning_1 = QtGui.QLabel(self.centralwidget)
        self.scanning_1.setGeometry(QtCore.QRect(130, 45, 16, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(20)
        self.scanning_1.setFont(font)
        self.scanning_1.setObjectName(_fromUtf8("scanning_1"))
        self.scanning_2 = QtGui.QLabel(self.centralwidget)
        self.scanning_2.setGeometry(QtCore.QRect(150, 45, 16, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(20)
        self.scanning_2.setFont(font)
        self.scanning_2.setObjectName(_fromUtf8("scanning_2"))
        self.scanning_3 = QtGui.QLabel(self.centralwidget)
        self.scanning_3.setGeometry(QtCore.QRect(170, 45, 16, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(20)
        self.scanning_3.setFont(font)
        self.scanning_3.setObjectName(_fromUtf8("scanning_3"))
        self.connecting_2 = QtGui.QLabel(self.centralwidget)
        self.connecting_2.setGeometry(QtCore.QRect(410, 85, 16, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(20)
        self.connecting_2.setFont(font)
        self.connecting_2.setObjectName(_fromUtf8("connecting_2"))
        self.connecting_1 = QtGui.QLabel(self.centralwidget)
        self.connecting_1.setGeometry(QtCore.QRect(390, 85, 16, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(20)
        self.connecting_1.setFont(font)
        self.connecting_1.setObjectName(_fromUtf8("connecting_1"))
        self.connecting_3 = QtGui.QLabel(self.centralwidget)
        self.connecting_3.setGeometry(QtCore.QRect(430, 85, 16, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(20)
        self.connecting_3.setFont(font)
        self.connecting_3.setObjectName(_fromUtf8("connecting_3"))
        self.bar = QtGui.QProgressBar(self.centralwidget)
        self.bar.setGeometry(QtCore.QRect(150, 380, 521, 31))
        self.bar.setMaximum(1023)
        self.bar.setProperty("value", 0)
        self.bar.setTextVisible(False)
        self.bar.setObjectName(_fromUtf8("bar"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 380, 31, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 290, 31, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.bar_2 = QtGui.QProgressBar(self.centralwidget)
        self.bar_2.setGeometry(QtCore.QRect(150, 290, 521, 31))
        self.bar_2.setMaximum(1)
        self.bar_2.setProperty("value", 0)
        self.bar_2.setTextVisible(False)
        self.bar_2.setObjectName(_fromUtf8("bar_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 290, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 380, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.chk_save_text = QtGui.QCheckBox(self.centralwidget)
        self.chk_save_text.setGeometry(QtCore.QRect(670, 210, 131, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.chk_save_text.setFont(font)
        self.chk_save_text.setObjectName(_fromUtf8("chk_save_text"))
        self.chk_save_db = QtGui.QCheckBox(self.centralwidget)
        self.chk_save_db.setGeometry(QtCore.QRect(670, 240, 131, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.chk_save_db.setFont(font)
        self.chk_save_db.setObjectName(_fromUtf8("chk_save_db"))
        self.btn_print_report = QtGui.QPushButton(self.centralwidget)
        self.btn_print_report.setGeometry(QtCore.QRect(480, 450, 120, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.btn_print_report.setFont(font)
        self.btn_print_report.setObjectName(_fromUtf8("btn_print_report"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 815, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.list_baud.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ModMen® Production | IoT", None))
        self.chk_remember.setText(_translate("MainWindow", "Remember Password", None))
        self.btn_scan.setText(_translate("MainWindow", "Scan Networks", None))
        self.btn_connect_wifi.setText(_translate("MainWindow", "Connect", None))
        self.btn_refresh_comm.setText(_translate("MainWindow", "⟳", None))
        self.btn_connect_serial.setText(_translate("MainWindow", "Connect", None))
        self.list_baud.setItemText(0, _translate("MainWindow", "4800", None))
        self.list_baud.setItemText(1, _translate("MainWindow", "9600", None))
        self.list_baud.setItemText(2, _translate("MainWindow", "19200", None))
        self.list_baud.setItemText(3, _translate("MainWindow", "115200", None))
        self.lbl_serial_connected.setText(_translate("MainWindow", "|", None))
        self.lbl_baud_rate.setText(_translate("MainWindow", "Baud Rate", None))
        self.lbl_serial.setText(_translate("MainWindow", "Serial Connection", None))
        self.lbl_wifi.setText(_translate("MainWindow", "WiFi Connection", None))
        self.lbl_wifi_connected.setText(_translate("MainWindow", "|", None))
        self.chk_show.setText(_translate("MainWindow", "Show Password", None))
        self.btn_start_acquisition.setText(_translate("MainWindow", "Start Acquisition", None))
        self.lbl_acquisition_2.setText(_translate("MainWindow", "Data Acquisition", None))
        self.lbl_acquisition.setText(_translate("MainWindow", "|", None))
        self.scanning_1.setText(_translate("MainWindow", "•", None))
        self.scanning_2.setText(_translate("MainWindow", "•", None))
        self.scanning_3.setText(_translate("MainWindow", "•", None))
        self.connecting_2.setText(_translate("MainWindow", "•", None))
        self.connecting_1.setText(_translate("MainWindow", "•", None))
        self.connecting_3.setText(_translate("MainWindow", "•", None))
        self.label.setText(_translate("MainWindow", "0", None))
        self.label_2.setText(_translate("MainWindow", "0", None))
        self.label_3.setText(_translate("MainWindow", "Digital Value", None))
        self.label_4.setText(_translate("MainWindow", "Analog Value", None))
        self.chk_save_text.setText(_translate("MainWindow", "Save to text file", None))
        self.chk_save_db.setText(_translate("MainWindow", "Save to database", None))
        self.btn_print_report.setText(_translate("MainWindow", "Print Report", None))

